const mongoose = require('mongoose');

// ─────────────────────────────────────────────────────────────
//  StudentRegister Model
//  Stores registered students with their face encodings.
//  Teacher registers students ONCE before any session.
//  Face encodings are used to identify students in videos.
// ─────────────────────────────────────────────────────────────

const studentRegisterSchema = new mongoose.Schema({

  // Which teacher registered this student
  teacherId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Teacher',
    required: true,
    index: true,
  },

  // Student details
  name: {
    type: String,
    required: [true, 'Student name is required'],
    trim: true,
  },

  prn: {
    type: String,
    required: [true, 'PRN is required'],
    trim: true,
  },

  className: {
    type: String,
    trim: true,
    default: '',
  },

  // Photo stored on disk
  photoPath: {
    type: String,
    default: null,
  },

  // 128-number face fingerprint generated by face_recognition
  // Stored as array of floats
  // null = photo not yet processed
  faceEncoding: {
    type: [Number],
    default: null,
  },

  // Whether face encoding was successfully generated
  encodingStatus: {
    type: String,
    enum: ['pending', 'success', 'failed'],
    default: 'pending',
  },

  encodingError: {
    type: String,
    default: null,
  },

}, { timestamps: true });

// Compound index — one PRN per teacher per class
studentRegisterSchema.index({ teacherId: 1, prn: 1 }, { unique: true });

module.exports = mongoose.model('StudentRegister', studentRegisterSchema);
